on:
  push:
    branches:
      - master # Change this to your main branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
 #       runs-on: ubuntu-latest
 #       steps:
  #        - uses: actions/checkout@v3
 #           with:
 #             fetch-depth: 0
        uses: docker://sonarsource/sonar-scanner-cli:latest
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}    

 

      - name: Set up Flutter
        uses: subosito/flutter-action@v5
        with:
          flutter-version: stable

 

      - name: Install dependencies
        run: flutter pub get
